os:
- linux
dist: bionic
language:
- cpp
cache: ccache
addons:
  apt:
    packages:
    - libboost-dev
    - libboost-program-options-dev
    - libboost-system-dev
    - libboost-test-dev
    - uuid-dev
    - libnss3-dev
    - libnss3-tools
    - libsasl2-dev
    - sasl2-bin
    - swig
    - valgrind
    - ruby

jobs:
  include:
    - name: "Build and test under python2"
      before_install:
      - export PATH=/home/travis/.local/bin:$PATH
      - export PYTHONPATH=/home/travis/.local/lib/python2.7/site-packages:$PYTHONPATH
      install:
      - pip install --user --upgrade pip
      - pip install --user qpid-python
      before_script:
      - mkdir Build
      - cd Build
      - pyenv versions
      - cmake .. -DCMAKE_INSTALL_PREFIX=$PWD/install -DPYTHON_EXECUTABLE="$(which python2)"
      script:
      - make -j$(nproc) && make install && ctest -V
    - name: "Build and test under python3"
      dist: focal
      before_install:
      - export PATH=/home/travis/.local/bin:$PATH
      - export PYTHONPATH=/home/travis/.local/lib/python3.8/site-packages:$PYTHONPATH
      before_script:
      - mkdir Build
      - cd Build
      - pyenv versions
      - PYENV_VERSION="3.8.3" cmake .. -DCMAKE_INSTALL_PREFIX=$PWD/install -DPYTHON_EXECUTABLE="$(which python3)"
      script:
      - make -j$(nproc) && make install && ctest -V

